import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import EAlogo from "./assets/EAthink.png";
import Navigation from "./components/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EA landing page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="h-16 bg-red-600 flex fixed w-full ">
          <div className="mx-auto">
            <Link className="h-16 w-16" href={"#top1"}>
              <Image
                src={EAlogo}
                alt="Home"
                className="h-16 w-16 hover:scale-95 transition-transform duration-500 ease-linear"
              ></Image>
            </Link>
          </div>
          <Navigation />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
